kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-sc
provisioner: kubernetes.io/{{PROVISIONER}}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: {{PROVISION_TYPE}}
