apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-controller-config
  namespace: "{{NAMESPACE}}"
data:
  CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
  KAFKA_COMPRESSION_TYPE: producer
  KAFKA_CONNECTIONS_MAX_IDLE_MS: "600000"
  KAFKA_CONTROLLED_SHUTDOWN_ENABLE: "true"
  KAFKA_CONTROLLED_SHUTDOWN_MAX_RETRIES: "3"
  KAFKA_CONTROLLED_SHUTDOWN_RETRY_BACKOFF_MS: "5000"
  KAFKA_CONTROLLER_LISTENER_NAMES: KAFKA-CONTROLLER
  KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-controller-0.kafka-controller-hs.default.svc.cluster.local:29093,1@kafka-controller-1.kafka-controller-hs.default.svc.cluster.local:29093,2@kafka-controller-2.kafka-controller-hs.default.svc.cluster.local:29093
  KAFKA_CONTROLLER_SOCKET_TIMEOUT_MS: "30000"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "2" # This is already set; ensure it's only defined once
  KAFKA_DELETE_TOPIC_ENABLE: "true"
  KAFKA_ENABLE_SSL_CERTIFICATE_VERIFICATION: "false"
  KAFKA_FETCH_PURGATORY_PURGE_INTERVAL_REQUESTS: "1000"
  KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: "300000"
  KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: "6000"
  KAFKA_INTER_BROKER_PROTOCOL_VERSION: "3.7"
  KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: "300"
  KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: "10"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: KAFKA-CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL
  KAFKA_LISTENERS: KAFKA-CONTROLLER://0.0.0.0:29093
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_LOG_CLEANER_BACKOFF_MS: "15000"
  KAFKA_LOG_CLEANER_DEDUPE_BUFFER_SIZE: "134217728"
  KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: "86400000"
  KAFKA_LOG_CLEANER_ENABLE: "true"
  KAFKA_LOG_CLEANER_IO_BUFFER_LOAD_FACTOR: "0.9"
  KAFKA_LOG_CLEANER_IO_BUFFER_SIZE: "524288"
  KAFKA_LOG_CLEANER_IO_MAX_BYTES_PER_SECOND: "1.7976931348623157E308"
  KAFKA_LOG_CLEANER_MIN_CLEANABLE_RATIO: "0.5"
  KAFKA_LOG_CLEANER_MIN_COMPACTION_LAG_MS: "0"
  KAFKA_LOG_CLEANER_THREADS: "1"
  KAFKA_LOG_CLEANUP_POLICY: delete
  KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: "9223372036854775807"
  KAFKA_LOG_FLUSH_OFFSET_CHECKPOINT_INTERVAL_MS: "60000"
  KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS: "9223372036854775807"
  KAFKA_LOG_INDEX_INTERVAL_BYTES: "4096"
  KAFKA_LOG_INDEX_SIZE_MAX_BYTES: "10485760"
  KAFKA_LOG_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS: "9223372036854775807"
  KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: CreateTime
  KAFKA_LOG_PREALLOCATE: "false"
  KAFKA_LOG_RETENTION_BYTES: "-1"
  KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
  KAFKA_LOG_RETENTION_HOURS: "4"
  KAFKA_LOG_ROLL_HOURS: "4"
  KAFKA_LOG_ROLL_JITTER_HOURS: "0"
  KAFKA_LOG_SEGMENT_BYTES: "1073741824"
  KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: "60000"
  KAFKA_MAX_CONNECTIONS_PER_IP: "2147483647"
  KAFKA_MESSAGE_MAX_BYTES: "10485760" # Updated from 32000000
  KAFKA_MIN_INSYNC_REPLICAS: "1"
  KAFKA_NUM_IO_THREADS: "8"
  KAFKA_NUM_NETWORK_THREADS: "3"
  KAFKA_BACKGROUND_THREADS: "10"
  KAFKA_NUM_PARTITIONS: "50" # Existing setting
  KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: "3" # Existing setting
  KAFKA_NUM_REPLICA_FETCHERS: "3" # Added
  KAFKA_OFFSET_METADATA_MAX_BYTES: "4096"
  KAFKA_OFFSETS_COMMIT_REQUIRED_ACKS: "-1"
  KAFKA_OFFSETS_COMMIT_TIMEOUT_MS: "5000"
  KAFKA_OFFSETS_LOAD_BUFFER_SIZE: "5242880"
  KAFKA_OFFSETS_RETENTION_CHECK_INTERVAL_MS: "600000"
  KAFKA_OFFSETS_RETENTION_MINUTES: "1440"
  KAFKA_OFFSETS_TOPIC_COMPRESSION_CODEC: "0"
  KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "50"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3" # Existing setting
  KAFKA_OFFSETS_TOPIC_SEGMENT_BYTES: "104857600"
  KAFKA_PROCESS_ROLES: controller
  KAFKA_PRODUCER_PURGATORY_PURGE_INTERVAL_REQUESTS: "1000"
  KAFKA_QUEUED_MAX_REQUESTS: "500"
  KAFKA_QUOTA_CONSUMER_DEFAULT: "9223372036854775807"
  KAFKA_QUOTA_PRODUCER_DEFAULT: "9223372036854775807"
  KAFKA_REPLICA_FETCH_BACKOFF_MS: "1000"
  KAFKA_REPLICA_FETCH_MAX_BYTES: "10485760" # Updated from 36700160
  KAFKA_REPLICA_FETCH_MIN_BYTES: "1"
  KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: "41943040" # Added
  KAFKA_REPLICA_FETCH_WAIT_MAX_MS: "500"
  KAFKA_REPLICA_HIGH_WATERMARK_CHECKPOINT_INTERVAL_MS: "5000"
  KAFKA_REPLICA_LAG_TIME_MAX_MS: "10000"
  KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: "65536"
  KAFKA_REPLICA_SOCKET_TIMEOUT_MS: "30000"
  KAFKA_REQUEST_TIMEOUT_MS: "30000"
  KAFKA_RESERVED_BROKER_MAX_ID: "1000"
  KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: "10485760" # Added
  KAFKA_SOCKET_SEND_BUFFER_BYTES: "10485760" # Added
  KAFKA_SOCKET_REQUEST_MAX_BYTES: "41943040" # Added
  KAFKA_SSL_CLIENT_AUTH: none
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  KAFKA_SSL_KEY_CREDENTIALS: broker_creds
  KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_creds
  KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_creds
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3" # Added
  KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "true"


