apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-controller
  name: kafka-controller-hs
  namespace: "{{NAMESPACE}}"
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-kafka-int
    port: 9092
    protocol: TCP
    targetPort: tcp-kafka-int
  - name: tcp-kafka-ssl
    port: 9093
    protocol: TCP
    targetPort: tcp-kafka-ssl
  - name: jmx
    port: 1234
    protocol: TCP
    targetPort: jmx
  selector:
    app: kafka-controller
  sessionAffinity: None
  type: ClusterIP
