#!/usr/bin/env bash


. /etc/kafka/docker/bash-config

# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
  for var in "$@"
  do
    export "$var"
  done
fi

echo "===> User"
id

echo "===> Setting default values of environment variables if not already set."
. /etc/kafka/docker/configureDefaults

echo "===> Configuring ..."
. /etc/kafka/docker/configure

echo "===> Launching ... "
. /etc/kafka/docker/launch
